[package]
name = "repeating-xor"
description = "My solution to the fifth challenge"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "*", features = ["cargo"] }
xor = { version = "0.1.0", path = "../lib/xor" }
hex = { version = "0.4.3" }