[package]
name = "single-byte-xor"
description = "My solution to the third challenge"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "*", features = ["cargo"] }
hex = { version = "0.4.3" }
xor = { version = "0.1.0", path = "../xor" }