# This folder contains all of my solutions to each challenge

[workspace]
members = [
    "lib/*", 
    "hex-to-base64",
    "fixed-xor",
    "single-byte-xor",
    "detect-single-byte-xor",
    "repeating-xor",
    "break-repeating-xor",
]