[package]
name = "hex-to-base64"
description = "The solution to first challenge"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = { version = "1.0.1" }
clap = { version = "*", features = ["cargo"] }
hex = { version = "0.4.3" }
base64 = { version = "0.1.0", path = "../lib/base64" } 